### ISSUE TITLE
enable inject related_obj into reconciler

### ISSUE THREAD

**Issue by zen-xu** [kube-rs/kube#1091]
### Would you like to work on this feature?

yes

### What problem are you trying to solve?

The reconciler callback function of the `Controller` does not currently support getting the related object.

### Describe the solution you'd like

Defining a trait `Reconciler` and implement it for `fn(Arc<K>, Arc<Ctx>)`, `fn(Arc<K>, Arc<Ctx>, Option<Box<ObjectRef<DynamicObject>>>)` and `fn(Arc<K>, Arc<Ctx>, ReconcileRequest<K>)`

Then the code can be like
```rust
async fn reconcile(
    generator: Arc<ConfigMapGenerator>,
    ctx: Arc<Data>,
    // without `related_obj` is also ok, this param will be injected by the applier
    related_obj: Option<Box<ObjectRef<DynamicObject>>>,
) -> Result<Action, Error> {
  todo!()
}

Controller::new(cmgs, ListParams::default())
    .owns(cms, ListParams::default())
    .reconcile_all_on(reload_rx.map(|_| ()))
    .shutdown_on_signal()
    .run_with_injection(reconcile, error_policy, Arc::new(Data { client }))
    .for_each(|res| async move {
        match res {
            Ok(o) => info!("reconciled {:?}", o),
            Err(e) => warn!("reconcile failed: {}", e),
        }
    })
    .await;
```

### Describe alternatives you've considered

None

### Target crate for feature

kube-runtime

**Comment by clux** [comment]
Hey. Thanks for starting a discussion on this. I do have some reservations about this as it stands;

First; `Option<Box<ObjectRef<DynamicObject>>>` does feel like a pretty awkward type to work with, but at least you've made it an opt-in thing to the reconciler future by creating a different run method.

Second; this does not actually help the user that much? They still have to fetch the object, and they have to dig this out of a pretty awkward new `Api` object made from `ObjectRef<DynamicObject>`.

Are we doing this to save on network traffic? If so, I am wondering if what we really want is to expose caches for the related objects instead?

Are we doing this to figure out "what work we need to do in the reconciler"? This is a type of error prone optimisation that kubernetes warns against doing in the first place. Make the reconciler idempotent and check everything.

**Comment by teozkr** [comment]
Yeah, I'm with @clux on this one. We explicitly don't expose the reason for the reconciliation to the reconciler, since often there will be more than one reason batched together.

This would also not be reliably useful, since:

1. Most of the time, the same "root" object can have multiple related objects (maybe even multiple related object types!)
2. If there are multiple related objects then which object "caused" the reconciliation is going to vary between reconciliations, which is likely to cause unpredictable or even flapping/looping reconciliation behaviour
3. Many reasons don't have a related object at all (root object was updated, re-reconciliation timer expired, etc), even if the reconciler expects one to exist

What use-case are you trying to solve with this?

**Comment by zen-xu** [comment]
That makes sense. I misunderstood the reconciler.

Appreciate your patience in replying
