### ISSUE TITLE
Add a debug feature to `Client` that can dump RBAC

### ISSUE THREAD

**Issue by clux** [kube-rs/kube#1115]
### Would you like to work on this feature?

maybe

### What problem are you trying to solve?

After having tested a controller or similar locally, I often need to hand-write RBAC (Role or ClusterRole) [`rules`](https://docs.rs/k8s-openapi/latest/k8s_openapi/api/rbac/v1/struct.PolicyRule.html). This can in-theory be automated to __some__ degree if we had a way to track the amount of calls and the type of calls that was being done within the `Client`.

### Describe the solution you'd like

Add a debug / `rbacgen` feature-flagged vector member to `Client` to track the amount of calls done, and populate this vector when calling any of the internal request methods (that `Api` ultimately calls).

This way users can run a `Controller` locally, and at some point, do `println!("{}, client.dump_rbac());` and put the result of that into a `Role` somehow.

### Describe alternatives you've considered

It is possible to do a [kubebuildery style thing](https://book.kubebuilder.io/reference/markers/rbac.html) on kube-derived'd `CustomResource`, but this would still require you to hand-write the rules (just in a different way in the code).

It's also (in-theory) possible to get this information **statically**, but it feels impractical to analyse the code to see what api calls are being made. Maybe in combination with #1108 it would be possible to do a fake-run on CI and get this type of output without having to make some kind of manual debug executable, but that would be much further down the line.

### Documentation, Adoption, Migration Strategy

Documentation can probably be put on kube.rs for this.

### Target crate for feature

kube-client

**Comment by clux** [comment]
A simpler, and more general generation method was suggested in the discord today;

- Create a temporary cluster with audit logging
- Run the controllers test scenarios
- Use https://github.com/liggitt/audit2rbac to extract rbac rules from the audit logs
- pipe result to rbac.yaml

I think that is probably a better approach, so it's probably not necessary to do the above suggestion.

Would like to see a script of how to do it for a controller so we can commit that into controller-rs, then will close this issue.

**Comment by clux** [comment]
Ok, have found a working solution for this in [controller-rs/justfile](https://github.com/kube-rs/controller-rs/blob/3576a3f563b6b2164df0a95a04963238a1cf768e/justfile#L77-L115). It does have some caveats:

- needs a full e2e setup, with dedicated cluster, test documents and proper waiting
- needs further formatting if it's to be injected into a chart
- needs further refinement if users want to enumerate namespaces rather than getting a `ClusterRole`

Have left a note about it in https://kube.rs/controllers/security/#rbac-access but think this solution is sufficient. Hard to do better inside the `Client`.

**Comment by samcday** [comment]
@clux out of interest, why was the [kubebuilder declarative style](https://book.kubebuilder.io/reference/markers/rbac.html) ruled out? I know it still needs to be maintained alongside the actual code that requires the RBAC, but it has the advantage of being much less complicated than the audit2rbac approach. Also with the declarative approach, there's less risk of excessive permissions being granted, since generally you'd sprinkle these declarations alongside the places where the actual calls are taking place.

**Comment by clux** [comment]
@samcday to be honest i don't particularly like the `audit2rbac` approach either, but it is only referenced in the [kube.rs/security](https://kube.rs/controllers/security/#rbac-access) part as an example way to help scope it.

(i do think there is a better way to fish actually used rbac `rules` out of the `Client` in the future (will write an issue for this) that does not require audit logs, but it still comes with some of the caveats for the kubebuilder style.)

### kubebuilder style
it has a lot of downsides;

- you need to wrap a lot of properties into awkward rawstring json annotations (the worst we currently do is [printcolumns](https://docs.rs/kube/latest/kube/derive.CustomResource.html#kubeprintcolumn--rjson) and those look bad enough in the example below) - it's an ugly api that is hard to give good errors for when the serialization/desirialization happen inside procmacro code
- when you create an encompassing api like this, it tends to become as complicated as the thing it needs to wrap over time (to allow people to change all the parts of the underlying api).. e.g.:
  * you might need to flip between `clusterrole` and `role` (your controller [does not have to use a clusterrole](https://kube.rs/controllers/security/#role-vs-clusterrole) even though that's what you get with kubebuilder - sometimes this is also an installation choice depending on controller operation mode)
  * you might want the namespace to be configurable (which is usually an installation choice)
  * you might want extra labels on the role for standardisation (usually a combined installation and operator choice)

so you end up with this api is either incomplete by design (or serves as an uglier wrapper), requires additional scripts to massage the output a format, and still needs to be user-overridable (like in the case you are creating a helm chart).

> with the declarative approach, there's less risk of excessive permissions being granted

i don't think this is true. the kubebuilder one gives you excessive permissions right off the bat with a clusterrole, but ignoring that, there's nothing stopping people not understanding rbac there and then and putting `groups="*", resources="*"` in there. this need to be tested for elsewhere. besides, if cluster operators understand rbac already, they are probably happier to see an editable yaml file, than a rust file with json annotations that they then have to learn to build.

so the current recommendation is that you write it yourself __somehow__. this way you can do it through helm/jsonnet for packaging.

**Comment by samcday** [comment]
Thanks for the in-depth reply! I see your points regarding kubebuilder-style. I think you might be misunderstanding some parts of the kubebuilder style though. Let me just make sure to internet-correct you in case those incorrect assumptions were to influence your decision :D

> and still needs to be user-overridable (like in the case you are creating a helm chart).

Uou *can* use that approach to augment a Helm chart. I did it here: https://github.com/samcday/hcloud-fip-k8s/blob/main/chart/generated/role.yaml

It's *slightly* hacky and will *only* work with the Helm chart. Which is fine for me because the Helm packaging is the native approach in that project anyway. If I also wanted static manifest support I'd generate them via `helm template`. This is because I actually placed the `{{ include }}` invocation in the [annotation in the code](https://github.com/samcday/hcloud-fip-k8s/blob/main/controllers/fipsetup/fipsetup.go#L22).

That file is generated [by controller-gen](https://github.com/samcday/hcloud-fip-k8s/blob/main/build.sh#L5), and then included into the [main templates](https://github.com/samcday/hcloud-fip-k8s/blob/main/chart/templates/rbac.yaml#L2). 

> excessive permissions right off the bat with a clusterrole

I'm not seeing this behaviour with controller-gen at all. Do you have an example? The generated RBAC I showed above *does* have a cluster role, but only specifically because I added [this annotation](https://github.com/samcday/hcloud-fip-k8s/blob/main/controllers/fipsetup/fipsetup.go#L21). i.e an annotation that *doesn't* specify a namespace.

> if cluster operators understand rbac already, they are probably happier to see an editable yaml file

Well the end result is still an editable YAML file, right? That's the whole point: you specify the annotations and then generate a "starter" RBAC. Cluster admins are still free to customize that however they wish. The annotations are just a convenience for the *developers*/*maintainers* in order to generate a distributable artifact containing the RBAC that makes the controller work by default.

> not understanding rbac there and then and putting groups="*", resources="*"

Yeah but ... I mean it's *even easier* to do that by just doing something very naughty like ... *cough* [this](https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/main/chart/templates/clusterrolebinding.yaml) I don't think the tooling should be blamed for bad behaviour or people choosing to ignore the mechanics of RBAC entirely :D

**Comment by samcday** [comment]
> you might want extra labels on the role for standardisation (usually a combined installation and operator choice)

Isn't this going to still be a problem with tools like audit2rbac? I haven't actually used that tool but from the README it doesn't seem like it supports setting arbitrary `labels` / `annotations`. You'd need to do that post-processing on the generated file yourself, right?

**Comment by clux** [comment]
> Isn't this going to still be a problem with tools like audit2rbac?

yep. the audit2rbac is also so wildly impractical to use in any automated way (if frequently gets too little rbac outputted) that it's kind of implied that you're not using it in any pipelined way. the kubebuilder way wants to be an automated solution for it though, and that's what i want to discourage, because it is insufficient.

**Comment by clux** [comment]
> I'm not seeing this behaviour with controller-gen at all. Do you have an example? The generated RBAC I showed above does have a cluster role, but only specifically because I added [this annotation](https://github.com/samcday/hcloud-fip-k8s/blob/main/controllers/fipsetup/fipsetup.go#L21). i.e an annotation that doesn't specify a namespace.

ah, thanks for that, yeah, misread the upstream doc. the header of the [linked kubebuilder doc](https://book.kubebuilder.io/reference/markers/rbac.html) said clusterrole in the header, but the namespace override fixes that.

> That file is generated [by controller-gen](https://github.com/samcday/hcloud-fip-k8s/blob/main/build.sh#L5), and then included into the [main templates](https://github.com/samcday/hcloud-fip-k8s/blob/main/chart/templates/rbac.yaml#L2).

it looks like you would have to basically copy the entire file to be able to customise labels though?

> It's slightly hacky and will only work with the Helm chart. Which is fine for me because the Helm packaging is the native approach in that project anyway. If I also wanted static manifest support I'd generate them via helm template. This is because I actually placed the {{ include }} invocation in the [annotation in the code](https://github.com/samcday/hcloud-fip-k8s/blob/main/controllers/fipsetup/fipsetup.go#L22).

yeah, it feels even hackier with carrying helm templates through kubebuilder :grimacing:

> Well the end result is still an editable YAML file, right? That's the whole point: you specify the annotations and then generate a "starter" RBAC. Cluster admins are still free to customize that however they wish. The annotations are just a convenience for the developers/maintainers in order to generate a distributable artifact containing the RBAC that makes the controller work by default.

well, if the file is generated from controller code, then PRs to that policy would now necessarily update the .go/rust code to update the yaml. effectively this means, it's no longer easily editable; contributions need to figure out, 1. what is missing in the yaml, 2. where in the chart that comes from, 3. where in the go code that comes from, 4. figure out what shell script to run to regenerate it all. 

as someone who probably finds it very easy to write rust controllers, i would much rather write rbac in yaml file directly. it's usually where people want to edit policy. you're already putting everything you wanted into the those annotations, why not write the rule directly?

**Comment by clux** [comment]
..i can see that you are getting some implicit access for `events` and `lease` access (even though i don't see leaderelection or event use in your code), but i can see it being a potentially helpful starter default.

tho if we are __only__ trying to solve the "starter yaml problem" then it's not much more helpful than adding docs ala:

```yaml
rules:
- apiGroups: ["YOURGROUP"]
  resources: ["YOURRESOURCE"]
  verbs: ["create", "delete" ,"get" ,"list" ,"patch" ,"update" ,"watch"]
# if you want events
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
# if you want leader election
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
```

and lean on people already knowing rbac. controller writing is already a fairly advanced cluster concept.

---

if we were to write code for rbac generation in kube, it imo should solve a bigger problem, like actually try to figure out what access we are using precisely.
