### ISSUE TITLE
Expose `default_namespace` on `Client`

### ISSUE THREAD

**Issue by jpmcb** [kube-rs/kube#1118]
### Would you like to work on this feature?

If this is something we'd like to do, I'd be happy to work on it! ❤️ 🦀 

### What problem are you trying to solve?

I need to be able to infer what namespace the controller code is in. This is possible with the incluster config creation / usage:

```rs
let incluster_config = kube::Config::incluster_dns()?;
let namespace = incluster_config.default_namespace;
```

But it's abit annoying to have to generate an incluster config in many different places. It'd be great if I could lift the config directly from the client (that created it).

### Describe the solution you'd like

I want to be able to do _something_ like:

```rs
let client = Client::try_default().await?;
let config = &client.config;
println!("The default namespace is {}", config.default_namespace);
```

This is something you can (sort of) do with client Go:

```go
// creates the in-cluster config
config, err := rest.InClusterConfig()
if err != nil {
	panic(err.Error())
}
// creates the clientset
clientset, err := kubernetes.NewForConfig(config)
if err != nil {
	panic(err.Error())
}
currentNamespace := config.Namespace()
```

Something similar in rust complains about the `Config` being moved/consumed. Maybe the solution here is to implement copy for the Client so it can be more easily moved around / used frequently?

### Describe alternatives you've considered

I may also be thinking of this the wrong way - any feedback welcome on this approach!

### Documentation, Adoption, Migration Strategy

N/a

### Target crate for feature

_Soon?_

**Comment by clux** [comment]
We don't really want to store the `Config` inside the `Client` since that's a lot of stuff to clone, and the data should already available in general from the `Config`, and when converting to a `Client`, we generally just move the data from the `Config` into where they are actually useful for it.

### Current Solutions
Two ways here should work based on your example:

```rust
let config = Config::infer().await?;
let client = Client::try_from(config.clone())?;
println!("The default namespace is {}", config.default_namespace);
```
or grab it first to avoid cloning the whole config:

```rust
let config = Config::infer().await?;
println!("The default namespace is {}", config.default_namespace);
let client = Client::try_from(config)?;
```

### Slightly easier extension
We could also simplify this by improving the internal `Client::default_ns` as an internal helper getter:
https://github.com/kube-rs/kube/blob/2d35a2f4d803285db6a32dff5124a17d69661030/kube-client/src/client/mod.rs#L129-L131

If we rename that to `Client::default_namespace`, document it, make it compile, then we can expose that directly from `Client`. This means you could do this at any point without stashing the config:

```rust
let client = Client::try_default().await?;
println!("The default namespace is {}", client.default_namespace());
```

Happy to take a PR for the latter.

**Comment by jpmcb** [comment]
Awesome! I'll submit a patch for this!
