### ISSUE TITLE
Allow collecting logs for jobs

### ISSUE THREAD

**Issue by andreclaudino** [kube-rs/kube#1157]
### Would you like to work on this feature?

yes

### What problem are you trying to solve?

Pods are almost the basic entity for kuberentes, but jobs and deployments have their importance in por management, but unfortunatelly, I can't get/stream logs from jobs using kube-rs.

The error says:

```
error[E0599]: the method `log_stream` exists for struct `kube::Api<Job>`, but its trait bounds were not satisfied
  --> server/src/kuberentes_client/watch.rs:15:38
   |
15 |         let mut log_stream = pod_api.log_stream(job_name, &log_params).await?.boxed();
   |                                      ^^^^^^^^^^ method cannot be called on `kube::Api<Job>` due to unsatisfied trait bounds

   = note: the following trait bounds were not satisfied:
           `Job: kube::api::Log`
```

### Describe the solution you'd like

We should implement kube::api::Log for Job.

### Describe alternatives you've considered

an alternative would be loading the logs of all pods related to a given a job.

**Comment by clux** [comment]
We don't currently support this because it's not a Kubernetes API primitive to show logs for jobs.
What actually happens (if you try `kubectl logs job/busibox -v=9`) is:

- GET https://localhost:49822/apis/batch/v1/namespaces/default/jobs/busybox (find the job, and its uid)
- GET https://localhost:49822/api/v1/namespaces/default/pods?labelSelector=controller-uid%3D1d8ec6b5-610f-4db9-9cf3-b71521a653e5 (lookup pod from the jobs uid)
- GET https://localhost:49822/api/v1/namespaces/default/pods/busybox-8s8sn/log?container=busybox (call logs on one matching pod)

As such it's not a feature we can actually put on `Api<Job>` because the workflow would involve multiple api queries against multiple kinds.

Maybe there's something to be said about having helpers for this in the future when working with direct client-v2 stuff (which is only early draft atm), but for now the way to do this is to follow kubectl style logic and do something like:

```rust
use kube::ResourceExt;

let jobs: Api<Job> = Api::default_namespaced(client.clone());
let pods: Api<Pod> = Api::default_namespaced(client.clone());
let job = jobs.get("job-name").await?;
let lp = ListParams::default().labels(format!("controller-uid={}", job.uid().unwrap()));
let matching_pods = pods.list(&lp).await?;
let chosen_pod = matching_pods.items.first().name_unchecked();

let logs = pods.logs(chosen_pod, &LogParams::default()).await;
```

should be roughly right, but haven't actually compile tested this. updates welcome.
