### ISSUE TITLE
Add option to emit stream of logs where each chunk represent a log line

### ISSUE THREAD

**Issue by goenning** [kube-rs/kube#1160]
### Would you like to work on this feature?

yes

### What problem are you trying to solve?

When I implemented the log_stream on my app, I was under the impression that each chunk of bytes from the stream would have exactly one log line.

For my use case, I care about each individual line because I need to prepend other stuff like container name, timestamp, etc.

In some cases the Kubernetes API seems to write multiple log lines which causes a visual mess like this:

![image](https://user-images.githubusercontent.com/94755/223418587-33be3cbb-7406-4048-b612-753ced70d849.png)

### Describe the solution you'd like

I found this commit https://github.com/kube-rs/kube/commit/2c8d7815b2663ae573735532849fa84d182c3b4d which seems to revert a previous implementation where the stream would buffer lines by looking for new line delimiter.

To avoid breaking changes, I would like to propose a new function:

```diff
impl<K> Api<K>
where
    K: DeserializeOwned + Log,
{
    /// Fetch logs as a string
    pub async fn logs(&self, name: &str, lp: &LogParams) -> Result<String> {
        let mut req = self.request.logs(name, lp).map_err(Error::BuildRequest)?;
        req.extensions_mut().insert("logs");
        self.client.request_text(req).await
    }

    /// Fetch logs as a stream of bytes
    pub async fn log_stream(&self, name: &str, lp: &LogParams) -> Result<impl Stream<Item = Result<Bytes>>> {
        let mut req = self.request.logs(name, lp).map_err(Error::BuildRequest)?;
        req.extensions_mut().insert("log_stream");
        self.client.request_text_stream(req).await
    }

+   /// Fetch logs as a stream of bytes where each chunk represent a log line
+   pub async fn log_stream_lines(&self, name: &str, lp: &LogParams) -> Result<impl Stream<Item = Result<Bytes>>> {
+       ...
+   }
}
```

### Describe alternatives you've considered

I can obviously implement this on my side, but it might be useful to have this on kube-rs, so I'm open to PR this.

### Target crate for feature

kube-client

**Comment by goenning** [comment]
IMO a separate function would be better, is all you need is just stream the logs to stdout or somewhere else, the existing function be better without all this extra dance to handle multiple lines. But I'm fine either way!

I didn't know about LinesCodec, does that make it easier to just pipe into the other stream? I'm not very familiar with futures/async, still learning!

This is a snippet of what I have, which I'm not proud, but it works for me! 😅 

```rust
        let new_line = b'\n';
        let mut prev_buffer = Vec::new();
        loop {
            match logs.try_next().await {
                Ok(Some(chunk)) => {
                    let chunk_lines = chunk.split_inclusive(|byte| *byte == new_line);
                    for chunk_line in chunk_lines {
                        prev_buffer.extend_from_slice(chunk_line);

                        // if the line ends with a new line, we have a complete log line
                        if chunk_line.ends_with(&[new_line]) {
                            let line_bytes = prev_buffer.drain(..);
                            emit(line_bytes.as_slice());
                        }
                    }
                }
                Ok(None) => ...
                Err(err) => ...
            }
        }
```

**Comment by clux** [comment]
> This is a snippet of what I have

hehe i am sure that works, but I would look at what we do with the [`LinesCodec`](https://docs.rs/tokio-util/latest/tokio_util/codec/struct.LinesCodec.html) with `FramedRead` + `StreamReader` in `request_events`. That would make it more portable (and it can also help us setup infinite watches in the future - as it stands log streams end up timing out just like regular watches).

> IMO a separate function would be better, if all you need is just stream the logs to stdout or somewhere else, the existing function be better without all this extra dance to handle multiple lines. But I'm fine either way!

hm, idunno, i feel this depends the breaking ends up interfering with normal streaming or not. like once we have received a full log-line it should be emitted without having to wait for the next one to break - which i assume will just work if each line is sent with a trailing newline. if this stuff just works then there's really not any major downside to have the extra layer in between. the expectation that people get one line per event is already there.

**Comment by clux** [comment]
One thing I noticed in tests the last couple of weeks as Kubernetes 1.26 has become more available in k3d on CI:

- log lines generally used to come in as one-line-per-chunk
- since 1.26 they now seem to come with potentially many lines per chunk

This caused CI test failures that were first fixed in https://github.com/kube-rs/kube/pull/1166 and we never saw these failures before these last weeks despite running for a year.

I honestly think we should just add in line buffering by default. It's probably what users expect (especially if they have set things up pre-1.26).

**Comment by aryan9600** [comment]
hello, I'd like to take this on. I had a question regarding the use of `LinesCode`. since `LinesCodec` decodes `Bytes` into `String`, would it be fine to change the item type of the returned stream from `Bytes` to `String`, i.e. `Result<impl Stream<Item = Result<String>>>`?
I'd assume that people assume logs to be strings anyway, so it should be fine and it'd save them the trouble of having to convert the [bytes into a string](https://github.com/kube-rs/kube/blob/5806a2d86f4d01ab7e0f01c40d1232e832d77c20/examples/log_stream.rs#L31-L33).

**Comment by clux** [comment]
Yeah. Personally, I think that's a reasonable default stance to take (use lossy utf8 decoding to string decode) in this day and age. [Kubernetes logging](https://kubernetes.io/docs/concepts/cluster-administration/logging/) uses their [CRI logging](https://github.com/kubernetes/design-proposals-archive/blob/main/node/kubelet-cri-logging.md) defaulting to JSON file and JSON [has to be UTF-8 encoded](https://en.wikipedia.org/wiki/JSON#Character_encoding).

<details><summary>That said (unnecessary rabbithole collapsible)</summary>
<p>

- [journald seems to allow binary data](https://www.freedesktop.org/software/systemd/man/systemd.journal-fields.html) (supported by cri logging)
- [filebeat allows setting custom encodings](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-container.html)
- [logstash allows setting charset](https://www.elastic.co/guide/en/logstash/current/plugins-codecs-plain.html)

so afaikt, there are no guarantees that rogue apps in customised clusters won't have non unicode seeping through somewhere, but i doubt even [kubectl logs](https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/logs/logs_test.go) would even handle this. their tests are all just using strings.

anyway, if people need to actually have complete accuracy of non utf-8 data, they probably won't be choosing logs to submit their data anyway given chances of failure at basically every level.
</p>
</details>

**Comment by aryan9600** [comment]
ah but unfortunately, `LinesCodec` [performs strict utf8 decoding](https://github.com/tokio-rs/tokio/blob/9dbf1879ee9c5846fe441ac5b0494c88b0f83ee3/tokio-util/src/codec/lines_codec.rs#L93-L96) instead of lossy utf8 decoding, which I think _might_ be a deal breaker as it could potentially break setups where some non-utf8 bytes are present and users were performing lossy utf8 decoding to get around that.
but on the other hand `kube_client::client::Client::request_text()` also seems to [perform strict utf8 decoding](https://github.com/kube-rs/kube/blob/f792fd22d7568496447012ace4fe2f13d0e59def/kube-client/src/client/mod.rs#L235) and given that this function is just a streamable counterpart of the former, one could make the argument that its fine to be strict about utf8 here as well.

**Comment by clux** [comment]
We've not had anyone complain about the encoding (nor have i seen any bugs about it in kubectl), so it's **probably still fine** to by default assume utf8 to allow us to return string lines for a nicer api.

It makes the most sense to me focus on the happy path first, and let cluster exploration tools (probably going to be the biggest user of this type of api, since most real log collection is usually done through the host nodes) gain the benefits from having buffered, full lines under an easy api. They could also potentially just skip errored lines if some fail initially. If it actually becomes a problem then people can raise an issue for more advanced usage.
