### ISSUE TITLE
Owned Resource Reconciliation

### ISSUE THREAD

**Issue by lswith** [kube-rs/kube#1167]
### Current and expected behavior

I'm currently using the `kube::runtime::Controller` to reconcile a "Build" CRD. This Build CRD creates a Pod which has an owner reference.

To keep the Build CRD status in sync with the Pod, I've watched the "owned" resources and run a reconciliation with each update of the Pod.

When I remove a Build, It seems there is always 2 Errors immediately afterwards:
```
{"level":"INFO","fields":{"message":"Reconciling build: build"},"target":"build_operator::controller"}
{"level":"INFO","fields":{"message":"removing build: build"},"target":"build_operator::controller"}
{"level":"INFO","fields":{"message":"Reconciliation successful","resource":"Build.v1alpha1.fl0.dev/build.fl0-build"},"target":"build_operator"}
{"level":"INFO","fields":{"message":"Reconciling build: build"},"target":"build_operator::controller"}
{"level":"INFO","fields":{"message":"removing build: build"},"target":"build_operator::controller"}
{"timestamp":"2023-03-21T06:59:28.718370Z","level":"ERROR","fields":{"message":"Reconciliation failed","error":"tried to reconcile object Build.v1alpha1.fl0.dev/build.fl0-build that was not found in local store"},"target":"build_operator"}
{"timestamp":"2023-03-21T06:59:28.723447Z","level":"ERROR","fields":{"message":"Reconciliation failed","error":"tried to reconcile object Build.v1alpha1.fl0.dev/build.fl0-build that was not found in local store"},"target":"build_operator"}
```

I think this is possibly due to the fact that kubernetes garbage collection is happening in the background and triggering the controller but I'm not entirely sure.

I would expect that I wouldn't get these 2 errors each time I remove a build.

### Environment

Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.24.10
WARNING: version difference between client (1.26) and server (1.24) exceeds the supported minor version skew of +/-1

linux/amd64

### Affected crates

kube-runtime

### Would you like to work on fixing this bug?

maybe

**Comment by clux** [comment]
Was looking into this to try to verify if there was anything we should do about this so thought to outline the (admittedly very) complicated stream flow to illustrate what is happening.

### Setup

1. main object deleted
2. child elements are deleted by Kubernetes around the same time (normal k8s gc; deleting objects whose ownerReferences matches the deleted parent object)

Both of these cause two events in our controller stream (assuming we have a `Controller::new(mainapi, cfg).owns(childapi, cfg)` type setup). 

### Cause

Both of these deletes cause watch events that end up in this closure in the main `applier` loop and will get scheduled:

https://github.com/kube-rs/kube/blob/6c9a53103b9c7a6fcfd0e503c7b2e0924f7d36ea/kube-runtime/src/controller/mod.rs#L294-L324

Note the `Runner` doesn't execute this closure until the [`scheduler` lets it through](https://github.com/kube-rs/kube/blob/6c9a53103b9c7a6fcfd0e503c7b2e0924f7d36ea/kube-runtime/src/controller/runner.rs#L108-L114C41), but this [generally happens almost immediately](https://github.com/kube-rs/kube/blob/6c9a53103b9c7a6fcfd0e503c7b2e0924f7d36ea/kube-runtime/src/controller/mod.rs#L277-L280) (for the first event), and the next one gets queued up for later (only one reconcile for the same object at a time), with potential deduplications on any further events happening while reconcile is going for that object ([dedupe/debounce source](https://github.com/kube-rs/kube/blob/6c9a53103b9c7a6fcfd0e503c7b2e0924f7d36ea/kube-runtime/src/scheduler.rs#L63-L81)).

This causes two of those above closures to be executed for the main object.

Now as you can see from your error messages the `store` in the closure **does not contain the object**  ([`ObjectNotFound`](https://github.com/kube-rs/kube/blob/6c9a53103b9c7a6fcfd0e503c7b2e0924f7d36ea/kube-runtime/src/controller/mod.rs#L43-L44)) because it was deleted.

We try to limit the amount of reconcile requests being scheduled for objects that do not exist; delete events from the main object are [actually filtered out (after reaching the store) and before getting into the applier](https://github.com/kube-rs/kube/blob/6c9a53103b9c7a6fcfd0e503c7b2e0924f7d36ea/kube-runtime/src/controller/mod.rs#L548-L551) (via [applied_objects](https://docs.rs/kube/latest/kube/runtime/trait.WatchStreamExt.html#method.applied_objects)).

However, we cannot do the same for delete events on child objects because we want delete events of managed resources to trigger reconciles of the main object (so they can be recreated). We do not have any information about what the "intent of the reconcile request" is once we are this far in, so we cannot say "oh, this came from a child, so we should check if the parent exists first" unfortunately, but then again, we also check if the resource exists anyway. So...

### Discussion

Are these errors actually a problem? Only visually. 

No guarantees are invalidated here, you will still not get reconcile hits about delete events **after** the deletion have happened.

Because the main object was **successfully** deleted, you did not have had a `finalizer` on the main object, and thus the delete was allowed to proceed without you getting any cleanup logic run.

The real question here is whether we should treat `ObjectNotFound` as an error case to be prominently logged as an error.

In your case, it is clearly not a real error because it's the expected process for related objects to trigger reconciles on non-existent objects.

However, there are legit cases where it is ought to produce an error; mappers from `Controller::watches` can produce object references to be reconciled that are garbage and do not exist, and these ought to show up as an indication that a controller dev is doing something wrong.

### Suggestions
It might make the most sense __for you__ to match on the [error type](https://docs.rs/kube/latest/kube/runtime/controller/enum.Error.html) from the output of `Controller::run` or in the `error_policy` (wherever you are doing the logging of errors) and filter out the `ObjectNotFound` error.

An internal suggestion for us; the fact that we are getting 2 of those errors rather than one is probably a debounce problem (#1247) that can maybe be improved separately (but it will not eliminate the problem entirely). Secondly, maybe it makes sense to have some error helpers or docs on this about owned streams in kube.rs.

**Comment by lswith** [comment]
understood. I'll close this ticket considering this is expected behaviour.

**Comment by DerRockWolf** [comment]
(I might be missing something, very new to rust and rust-rs 🙂)

From what I can tell the `error_policy` callback function is only called when `reconciler` returns an `Err`. The callback is called before the `Item` is "added" to the `Stream` that is returned by the `run` method.

The `ObjectNotFound` error however is not thrown (at least not in the case of this issue) by the `reconciler` function so the statement:

> It might make the most sense for you to match on the [error type](https://docs.rs/kube/latest/kube/runtime/controller/enum.Error.html) from the output of `Controller::run` or in the `error_policy` (wherever you are doing the logging of errors) and filter out the ObjectNotFound error.

Is partially false as the `ObjectNotFound` error cannot be handled in the `error_policy` and must be done using the output of the `run` method.

**Comment by clux** [comment]
> The `ObjectNotFound` error however is not thrown (at least not in the case of this issue) by the `reconciler` function so the statement [..] Is partially false as the `ObjectNotFound` error cannot be handled in the `error_policy` and must be done using the output of the `run` method.

Ah, yes, i believe you are right about that. Thank you.
