### ISSUE TITLE
Implement refreshing for OIDC token

### ISSUE THREAD

**Issue by Razz4780** [kube-rs/kube#1223]
### Would you like to work on this feature?

yes

### What problem are you trying to solve?

When OIDC is configured as the authentication method in the kubeconfig, the token is never refreshed. It ends up in the `kube_client::client::auth::Auth::Bearer` variant.

### Describe the solution you'd like

Implement OIDC as another variant of `kube_client::client::auth::RefreshableToken`.

### Describe alternatives you've considered

None, we need this for the users of our project.

### Target crate for feature

kube-client

**Comment by aviramha** [comment]
Small typo - OIDC

**Comment by clux** [comment]
Work to help out with this would certainly be welcome, although this is probably not an easy feature, given the sizeable amount of code in auth/mod and auth/oauth.

From a quick look, it looks like this would need extra logic in:
- `TryFrom<&AuthInfo> for Auth` around the `ProviderToken::Oidc` to deal with access tokens and expiry properties
- `RefreshableToken` new variant for `::Oidc` to actually handle the refreshing
- an provider impl in `oauth.rs` ala `Gcp` struct to actually refresh the token using oidc

the last part is probably the hardest since currently the `Gcp` one defers to the `tame_oauth` crate (which afaikt is gcp only).

(This was from 30m of looking though, you may find that it is not so difficult looking.)

At any rate, if you are keen to try this out experiments/implementations or information about what is needed would very much be appreciated, and I will help at least review implementations.
