### ISSUE TITLE
`ApiGroup::recommended_kind` returns `None` while I expected `Some(_)`

### ISSUE THREAD

**Issue by xMAC94x** [kube-rs/kube#1289]
### Current and expected behavior

I would expect for `ApiGroup::recommended_kind` to return a kind when one exists. And only return None when no viable kind exist.

Imagine 2 CRD deployed `KindA` and `KindB`. both in the same group `example.com` 
`KindA` has versions `v1` and `v2`.
`KindB` only supports `v1`.

Now running `recommended_kind` for `KindB` will result in the following.

The code of https://github.com/kube-rs/kube/blob/0.85.0/kube-client/src/discovery/apigroup.rs#L301 will first detect the preferable version, which is `v2` and now it does not find any kind supporting this.

So the coding asserts that all Kinds in a Group support the same version.
I would either expect a change in that behavior and fall back to v1. or at least add a comment to the function so that its clear that it might return None, even if there working versions available, when another kind in a similar group has a newer version. And link to the `resources_by_stability` function.

### Possible solution

I am not 100% sure if this is a documentation bug or a actual behavior bug.
In case of a documentation bug. Add the documentation to make people aware of this constellation.

Otherwise, we need to check other versions, if the loop finished and the return inside wasnt hit.

### Environment

```
 [
  (ApiResource { group: "example.com", version: "v1", api_version: "example.com/v1", kind: "KindA", plural: "KindAs" }, ApiCapabilities { scope: Namespaced, subresources: [...], operations: [...] }), 
  (ApiResource { group: "example.com", version: "v2", api_version: "example.com/v2", kind: "KindA", plural: "KindAs" }, ApiCapabilities { scope: Namespaced, subresources: [...], operations: [...] }), 
  (ApiResource { group: "example.com", version: "v1", api_version: "example.com/v1", kind: "KindB", plural: "KindBs" }, ApiCapabilities { scope: Namespaced, subresources: [...], operations: [...] }), 
 ]
 ```

```
Client Version: v1.27.4
Kustomize Version: v5.0.1
Server Version: v1.25.10
```

### Configuration and features

```toml
k8s-openapi = { version = "0.19", features = ["v1_27"] }
kube = { version = "0.85", features = ["runtime", "client"] }
```

### Would you like to work on fixing this bug?

maybe

**Comment by clux** [comment]
Thanks for reporting / writing this down. This is definitely one of those strange footguns that everyone is confused by. It still feels like a documentation issue to me, because it kind falls out of the [upstream api](https://github.com/kube-rs/kube/blob/e531d836d0573fe010259f9f2f44f6261d988aa0/kube-client/src/client/mod.rs#L366-L375) (that returns [APIGroupList](https://docs.rs/k8s-openapi/latest/k8s_openapi/apimachinery/pkg/apis/meta/v1/struct.APIGroupList.html) containing [APIGroup](https://docs.rs/k8s-openapi/latest/k8s_openapi/apimachinery/pkg/apis/meta/v1/struct.APIGroup.html)s) that a `preferred_version` is a **group-wide concept** (and so you should probably version resources in a group consistently).

This is not at all intuitive though. It kind of also discourages version changes imo.

It would at the very least make sense to add a paragraph or two about it under our [ApiGroup](https://github.com/kube-rs/kube/blob/6e75057f1a1f148dbd7a446a67ffbc23fb09ab1d/kube-client/src/discovery/apigroup.rs#L11-L63) or the main [methods where people are likely to read about preferred versions](https://github.com/kube-rs/kube/blob/e531d836d0573fe010259f9f2f44f6261d988aa0/kube-client/src/discovery/apigroup.rs#L185-L200).
