### ISSUE TITLE
HTTP proxy support

### ISSUE THREAD

**Issue by Razz4780** [kube-rs/kube#1361]
### Would you like to work on this feature?

yes

### What problem are you trying to solve?

`kube-client` crate currently supports only SOCKS5 proxies in the kubeconfig (`config.proxy_url`, `HTTP[S]_PROXY`/`http[s]_proxy` env variables). Relevant code starts [here](https://github.com/kube-rs/kube/blob/44932971fe12ddeebde4a85bb92b8a2fb7f0e5e3/kube-client/src/client/builder.rs#L76). However, proxy can also use the regular HTTP protocol.

### Describe the solution you'd like

Inspect scheme of the proxy URI and optionally wrap the base connector with [hyper_proxy](https://docs.rs/hyper-proxy/latest/hyper_proxy/). Hide it behind a new feature `http_proxy` (name suggestions welcome).

Found some past discussions on this:
https://github.com/kube-rs/kube/discussions/1010
https://github.com/kube-rs/kube/pull/837

### Describe alternatives you've considered

None so far

### Target crate for feature

kube-client

**Comment by clux** [comment]
I like the proposal of this in theory because I would also like to support it, but it has one problem practically; the proposed crate has not had a release in [over 2 years](https://crates.io/crates/hyper-proxy).

If we were to do this, I would personally prefer to do it after the hyper 1.0 upgrade in #1351 (since we are already having to deal with infrequently updated connector libraries there and this feature would compound that). Waiting for 1.0 would mean getting a 1.0 upgrade pushed up into hyper-proxy first though.

**Comment by aviramha** [comment]
We have implemented it in our fork, and now that the hyper 1.0 upgrade is done we shall send a PR :)
