### ISSUE TITLE
Add method to WatchStreamExt to get  object that event type is deleted

### ISSUE THREAD

**Issue by 3Xpl0it3r** [kube-rs/kube#1399]
### Would you like to work on this feature?

no

### What problem are you trying to solve?

I want to classfiy pod by event type(add/update/delete), but none of method in WatchStreamExt can do this; 

### Describe the solution you'd like

so should we add an method eg 'deleted_objects' into WatchStreamExt trait?

### Describe alternatives you've considered

i have no more idea;

**Comment by nightkr** [comment]
Hey, you can already do this by pattern-matching on [`watcher::Event`](https://docs.rs/kube/0.88.1/kube/runtime/watcher/enum.Event.html). However, it's a bit more tricky than watching for updated objects, since objects can be deleted while your controller isn't running, or while it has lost connection to the API. Hence, the actual answer depends on what you're trying to accomplish.

### If you're managing _transient_/internal state, where you're okay throwing everything away and starting over on a restart:

```rust
my_watcher.and_then(|event| async move {
  match event {
    watcher::Event::Deleted(o) => { ... } // o was deleted
    watcher::Event::Restarted(os) => { ... } // everything except os was deleted, probably drop internal state and start over?
    watcher::Event::Applied(_) => Ok(()), // object was updated, ignore
  }
})
```

### If you're managing _external_ state, that you need to keep in sync with K8s:

You'll want to delay Kubernetes from deleting your objects until you have had time to sync that deletion to whatever external resource you're managing. Consider using a [`Controller`](https://docs.rs/kube/0.88.1/kube/runtime/struct.Controller.html) with [`finalizer`](https://docs.rs/kube/0.88.1/kube/runtime/finalizer/fn.finalizer.html).
