### ISSUE TITLE
Access Kubelet exec/logs/portforward endpoints

### ISSUE THREAD

**Issue by XciD** [kube-rs/kube#1425]
### Would you like to work on this feature?

Yes

### What problem are you trying to solve?

I order to avoid api server overload, I'd like to access the kubelet api directly for `exec`, `logs`, `portforward`

https://github.com/kubernetes/kubernetes/blob/b3926d137cd2964cd3a04088ded30845910547b1/pkg/kubelet/server/server.go#L454

I've done it manually for logs as the stream is easy to consume, but for exec it's a little more complicated and `AttachedProcess` struct is not publicly available.

### Describe the solution you'd like

I would like to use the `exec` method directly into the node maybe with a client new method `is_node()` ?

### Describe alternatives you've considered

I've tried to create a new kube client with the node ip + a new resources to override `url_path` but the kubelet path is very different from the api server: `/exec/{podNamespace}/{podID}/{containerName}`

https://github.com/kube-rs/kube/blob/df37c999a967616c9e58b59e0dbcc13d2a0165ee/kube-core/src/subresource.rs#L337

### Target crate for feature

kube-client

**Comment by clux** [comment]
How are you hitting the kubelet directly? You doing some type of [raw requests](https://github.com/kube-rs/kube/blob/df37c999a967616c9e58b59e0dbcc13d2a0165ee/examples/request_raw.rs) with [node log queries](https://kubernetes.io/blog/2023/04/21/node-log-query-alpha/#how-do-i-use-it) ?

i am not aware that you can do that directly for more advanced stuff? at the very least that would be a lot more complicated to do manually due to the need for an http upgrade into websockets. is this possible in client-go / kubectl?

**Comment by XciD** [comment]
> How are you hitting the kubelet directly? You doing some type of [raw requests](https://github.com/kube-rs/kube/blob/df37c999a967616c9e58b59e0dbcc13d2a0165ee/examples/request_raw.rs) with [node log queries](https://kubernetes.io/blog/2023/04/21/node-log-query-alpha/#how-do-i-use-it) ?

I use a reqwest http client with a service account jwt. Quite simple for pod logs as it's a simple stream.


> i am not aware that you can do that directly for more advanced stuff? at the very least that would be a lot more complicated to do manually due to the need for an http upgrade into websockets. is this possible in client-go / kubectl?

Yeah, purpose was to bypass api server to remove some load and reduce latencies. And, no, not possible in client-go, kubectl. In fact, I didn't check as we drop of go long ago. For sure, is that the api server is using those endpoint to exec/log/etc

**Comment by XciD** [comment]
Some working example: https://github.com/XciD/kube/pull/1
Not sure if it's the right way to implement it on the lib tho

**Comment by clux** [comment]
Ah, that is interesting! I am curious to see if there are any perceivable differences between the original portforward and exec .

I see you are using:
- yours: `format!("/exec/{namespace}/{name}/{}?", ap.container.as_ref().cloned().unwrap_or_default())`
- ours: `format!("{}/{}/exec?", self.url_path, name)`
and
- yours: `format!("/portForward/{namespace}/{name}?")`
- ours:  `format!("{}/{}/portforward?", self.url_path, name)`

which seems to invert the order of the api arguments (exec before the resource identifiers) and add an extra name.
this does mean it undermines `Resource::url_path` a little bit and is thus a special case thing.

Because of this, maybe it's not a thing we add to `Api` (with a NodeExec trait implemented for Api<Pod>) but maybe it's a thing we add to `Client` directly (like many other low-level interfaces that's not tied to a resource). The `kube-core` stuff makes sense to me though.

---

Afaikt this is also an opt-in in the [kubelet via flag](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/) or config
```
--enable-debugging-handlers     Default: true
Enables server endpoints for log collection and local running of containers and commands. (DEPRECATED: This parameter should be set via the config file specified by the kubelet's --config flag. See [kubelet-config-file](https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/) for more information.)
```

so it should probably be documented as such (at the very least if it tends to not be enabled by default).

at any rate, am happy to have support for this!

**Comment by XciD** [comment]
I've updated the PR with your idea.

If you think I can create a PR targeting your repo, tell me, will change the target.

**Comment by clux** [comment]
I like it! Yeah, that would be great. I do have a few minor requests if you are able to:

- maybe factor out the (namespace, name, container) variable into a struct
- unit tests on kube-core requests should be easy to add (lots of similar examples in request side)
- one `#[ignore = "needs kubelet debug methods"]`'d integration test in kube-client (could just try to see that you can call node logs, as a minor sanity to try locally)

**Comment by XciD** [comment]
> - maybe factor out the (namespace, name, container) variable into a struct

Done :)

> - unit tests on kube-core requests should be easy to add (lots of similar examples in request side)

Done :)

> - one #[ignore = "needs kubelet debug methods"]'d integration test in kube-client (could just try to see that you can call node logs, as a minor sanity to try locally)

Done :)

**Comment by XciD** [comment]
Closed by https://github.com/kube-rs/kube/pull/1428
