### ISSUE TITLE
Namespace scoped access for `Controller.owns`

### ISSUE THREAD

**Issue by wseaton** [kube-rs/kube#941]
### Would you like to work on this feature?

maybe

### What problem are you trying to solve?

When trying to limit the scope of permissions required for a controller, it would be ideal if the client could be configured to only use namespace APIs, as reflection through the ownerreferences should inform the controller enough to do only a namespaced scoped call. 

Currently the controller runtime requires passing in a cluster scoped API for both the parent resource and it's child, which is not ideal for potentially sensitive resources like `Secrets` or `ConfigMap`s.

### Describe the solution you'd like

Another method on `Controller` like `owns_namespaced` where we pass in a client generic over namespace but not the resource might work?

### Describe alternatives you've considered

Haven't really considered other alternatives. 

### Target crate for feature

kube-runtime

**Comment by clux** [comment]
It should not be required to pass in a cluster scoped `Api`. Where are you getting this assumption from? `Controller::owns` should inherit the scope of the `Api` you pass in - because it just takes the events passed from a watch on that `Api`.

You should be able to either pass a `Api::namespaced(..)` or a `Api::all` to watch at the cluster level.

**Comment by teozkr** [comment]
If you know the NSes you want to watch at startup time then you could do something like:

```rust
Controller::new(...)
  .owns(Api::<Secret>::namespaced("ns1"))
  .owns(Api::<Secret>::namespaced("ns2"))
  .owns(Api::<Secret>::namespaced("ns..."))
  .run(...)
```

If you want to control which NSes you watch at runtime then it gets a bit trickier.. it should still technically be possible, but you'd probably need to use the low-level [`applier`](https://docs.rs/kube/latest/kube/runtime/controller/fn.applier.html) API directly rather than `Controller`.

**Comment by wseaton** [comment]
> If you want to control which NSes you watch at runtime then it gets a bit trickier.. it should still technically be possible, but you'd probably need to use the low-level [applier](https://docs.rs/kube/latest/kube/runtime/controller/fn.applier.html) API directly rather than Controller.

This looks promising, for my use-case a project can "opt-in" to management by our controller at any time, so runtime control is ideal (I'd make it externally triggered by another CRD). Would this be a good candidate for eventually exposing in `Controller`? Or better as a one-off recipe if I can figure it out.

**Comment by teozkr** [comment]
I don't think the "full journey" will ever have direct first-class support in `Controller`. I think there might be value in exposing "also listen to this arbitrary `Stream<Item = ObjectRef<K>>`" as an escape hatch (like the trigger queue that `applier` takes).

**Comment by teozkr** [comment]
Controller (Savage)

**Comment by clux** [comment]
Going to close this. Resolved question.
